export const plataformaicono = {
    "PC": "img/windows.svg", 
    "PlayStation 5": "img/playstation.svg",
    "PlayStation 4": "img/playstation.svg",
    "Xbox One": "img/xbox.svg",
    "Xbox Series S/X": "img/xbox.svg",
    "Nintendo Switch": "img/nintendo.svg",
    "iOS": "img/ios.svg",
    "Android": "img/android.svg",
    "Nintendo 3DS": "img/nintendo.svg",
    "Nintendo DS": "img/nintendo.svg",
    "Nintendo DSi": "img/nintendo.svg",
    "macOS": "img/apple.svg",
    "Linux": "img/linux.svg",
    "Xbox 360": "img/xbox.svg",
    "Xbox": "img/xbox.svg",
    "PlayStation 3": "img/playstation.svg",
    "PlayStation 2": "img/playstation.svg",
    "PlayStation": "img/playstation.svg",
    "PS Vita": "img/playstation.svg",
    "PSP": "img/playstation.svg",
    "Wii U": "img/nintendo.svg",
    "Wii": "img/nintendo.svg",
    "GameCube": "img/nintendo.svg",
    "Nintendo 64": "img/nintendo.svg",
    "Game Boy Advance": "img/nintendo.svg",
    "Game Boy Color": "img/nintendo.svg",
    "Game Boy": "img/nintendo.svg",
    "SNES": "img/nintendo.svg",
    "NES": "img/nintendo.svg",
    "Classic Macintosh": "img/apple.svg",
    "Apple II": "img/apple.svg",
    "Commodore / Amiga": "img/commodore.svg",
    "Atari 7800": "img/atari.svg",
    "Atari 5200": "img/atari.svg",
    "Atari 2600": "img/atari.svg",
    "Atari Flashback": "img/atari.svg",
    "Atari 8-bit": "img/atari.svg",
    "Atari ST": "img/atari.svg",
    "Atari Lynx": "img/atari.svg",
    "Atari XEGS": "img/atari.svg",
    "Genesis": "img/sega.svg",
    "SEGA Saturn": "img/atari.svg",
    "SEGA CD": "img/sega.svg",
    "SEGA 32X": "img/sega.svg",
    "SEGA Master System": "img/sega.svg",
    "Dreamcast": "img/sega.svg",
    "3DO": "img/panasonic.svg",
    "Jaguar": "img/atari.svg",
    "Game Gear": "img/sega.svg",
    "Neo Geo": "img/snk.svg",
    "Web": "img/web.svg",
  };
  